version: '3'
services:
  mongo:
    container_name: mongo_container
    image: "mongo:3.6.8-stretch"
    ports:
      - "27017:27017"
    networks:
      - teamnetwork
    ulimits:
      nofile: 65536
      # memlock:
      #   soft: -1
      #   hard: 1
    volumes:
      - mongodata:/data/db
  prom:
    container_name: prometheus_container
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - teamnetwork
    volumes:
      - "/vagrant/prometheus.yml:/etc/prometheus/prometheus.yml"
volumes:
  mongodata:
networks:
  teamnetwork:
